openapi: 3.1.0
info:
  description: The ConductorOne API is a HTTP API for managing ConductorOne resources.
  title: ConductorOne Access Conflict Webhook API
  version: 0.1.0-alpha
servers:
- description: The ConductorOne API server for the current tenant.
  url: https://{tenantDomain}.conductor.one
  variables:
    tenantDomain:
      default: example
      description: The domain of the tenant to use for this request.
security:
- bearerAuth: []
  oauth: []
tags:
- name: Webhook
paths:
  /api/v1/search/webhooks:
    post:
      description: Invokes the c1.api.webhooks.v1.WebhooksSearch.Search method.
      operationId: c1.api.webhooks.v1.WebhooksSearch.Search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksSearchRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksSearchResponse'
          description: Successful response
      summary: Search
      tags:
      - Webhook
      x-speakeasy-entity-operation:
        terraform-datasource:
        - Webhook#read
        - Webhooks#read
        terraform-resource: null
      x-speakeasy-group: WebhooksSearch
      x-speakeasy-name-override: Search
      x-speakeasy-pagination:
        inputs:
        - in: requestBody
          name: pageToken
          type: cursor
        outputs:
          nextCursor: $.nextPageToken
        type: cursor
  /api/v1/webhooks:
    get:
      description: Invokes the c1.api.webhooks.v1.WebhooksService.List method.
      operationId: c1.api.webhooks.v1.WebhooksService.List
      parameters:
      - in: query
        name: page_size
        schema:
          description: The pageSize field.
          format: int32
          readOnly: false
          type: integer
      - in: query
        name: page_token
        schema:
          description: The pageToken field.
          readOnly: false
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceListResponse'
          description: Successful response
      summary: List
      tags:
      - Webhook
      x-speakeasy-group: Webhooks
      x-speakeasy-name-override: List
    post:
      description: Invokes the c1.api.webhooks.v1.WebhooksService.Create method.
      operationId: c1.api.webhooks.v1.WebhooksService.Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceCreateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceCreateResponse'
          description: Successful response
      summary: Create
      tags:
      - Webhook
      x-speakeasy-entity-operation:
        terraform-resource: Webhook#create
      x-speakeasy-group: Webhooks
      x-speakeasy-name-override: Create
  /api/v1/webhooks/{id}:
    delete:
      description: Invokes the c1.api.webhooks.v1.WebhooksService.Delete method.
      operationId: c1.api.webhooks.v1.WebhooksService.Delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: The id field.
          readOnly: false
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceDeleteRequestInput'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceDeleteResponse'
          description: Empty response body. Status code indicates success.
      summary: Delete
      tags:
      - Webhook
      x-speakeasy-entity-operation:
        terraform-resource: Webhook#delete
      x-speakeasy-group: Webhooks
      x-speakeasy-name-override: Delete
    get:
      description: Invokes the c1.api.webhooks.v1.WebhooksService.Get method.
      operationId: c1.api.webhooks.v1.WebhooksService.Get
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: The id field.
          readOnly: false
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceGetResponse'
          description: Successful response
      summary: Get
      tags:
      - Webhook
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: Webhook#read
      x-speakeasy-group: Webhooks
      x-speakeasy-name-override: Get
    post:
      description: Invokes the c1.api.webhooks.v1.WebhooksService.Update method.
      operationId: c1.api.webhooks.v1.WebhooksService.Update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: The id field.
          readOnly: false
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceUpdateRequestInput'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceUpdateResponse'
          description: Successful response
      summary: Update
      tags:
      - Webhook
      x-speakeasy-entity-operation:
        terraform-resource: Webhook#update
      x-speakeasy-group: Webhooks
      x-speakeasy-name-override: Update
  /api/v1/webhooks/{id}/test:
    post:
      description: Invokes the c1.api.webhooks.v1.WebhooksService.Test method.
      operationId: c1.api.webhooks.v1.WebhooksService.Test
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: The id field.
          readOnly: false
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceTestRequestInput'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/c1.api.webhooks.v1.WebhooksServiceTestResponse'
          description: Successful response
      summary: Test
      tags:
      - Webhook
      x-speakeasy-group: Webhooks
      x-speakeasy-name-override: Test
components:
  schemas:
    c1.api.webhooks.v1.WebhooksServiceUpdateResponse:
      description: The WebhooksServiceUpdateResponse message.
      properties:
        webhook:
          $ref: '#/components/schemas/c1.api.webhooks.v1.Webhook'
      title: Webhooks Service Update Response
      type: object
      x-speakeasy-name-override: WebhooksServiceUpdateResponse
    c1.api.webhooks.v1.WebhooksServiceTestResponse:
      description: The WebhooksServiceTestResponse message.
      properties:
        webhook:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookInstance'
      title: Webhooks Service Test Response
      type: object
      x-speakeasy-name-override: WebhooksServiceTestResponse
    c1.api.webhooks.v1.WebhookInstance:
      description: The WebhookInstance message.
      properties:
        attempts:
          description: The attempts field.
          format: int32
          readOnly: false
          type: integer
        completedAt:
          format: date-time
          readOnly: true
          type: string
        createdAt:
          format: date-time
          readOnly: true
          type: string
        expiresAt:
          format: date-time
          readOnly: true
          type: string
        id:
          description: The id field.
          readOnly: false
          type: string
        lastAttemptedAt:
          format: date-time
          readOnly: true
          type: string
        source:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSource'
        spec:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSpec'
        state:
          description: The state field.
          enum:
          - WEBHOOK_STATE_UNSPECIFIED
          - WEBHOOK_STATE_PENDING
          - WEBHOOK_STATE_RUNNING
          - WEBHOOK_STATE_ERROR
          - WEBHOOK_STATE_WAITING_CALLBACK
          - WEBHOOK_STATE_PROCESS_RESPONSE
          - WEBHOOK_STATE_SUCCESS
          - WEBHOOK_STATE_FATAL_ERROR
          readOnly: false
          type: string
          x-speakeasy-unknown-values: allow
        updatedAt:
          format: date-time
          readOnly: true
          type: string
        webhookId:
          description: The webhookId field.
          readOnly: false
          type: string
      title: Webhook Instance
      type: object
      x-speakeasy-name-override: WebhookInstance
    c1.api.webhooks.v1.WebhookSpec:
      description: The WebhookSpec message.
      properties:
        destination:
          description: The destination field.
          readOnly: false
          type: string
      title: Webhook Spec
      type: object
      x-speakeasy-name-override: WebhookSpec
    c1.api.webhooks.v1.WebhooksServiceDeleteResponse:
      description: Empty response body. Status code indicates success.
      title: Webhooks Service Delete Response
      type: object
      x-speakeasy-name-override: WebhooksServiceDeleteResponse
    c1.api.webhooks.v1.WebhooksServiceUpdateRequestInput:
      description: The WebhooksServiceUpdateRequest message contains the webhook object to update and a field mask to indicate which fields to update. It uses URL value for input.
      properties:
        updateMask:
          nullable: true
          readOnly: false
          type: string
        webhook:
          $ref: '#/components/schemas/c1.api.webhooks.v1.Webhook'
      title: Webhooks Service Update Request
      type: object
      x-speakeasy-name-override: WebhooksServiceUpdateRequest
    c1.api.webhooks.v1.WebhookSource.WebhookSourceTest:
      description: The WebhookSourceTest message.
      nullable: true
      title: Webhook Source Test
      type: object
      x-speakeasy-name-override: WebhookSourceTest
    c1.api.webhooks.v1.WebhooksSearchRequest:
      description: The WebhooksSearchRequest message.
      properties:
        pageSize:
          description: The pageSize field.
          format: int32
          readOnly: false
          type: integer
        pageToken:
          description: The pageToken field.
          readOnly: false
          type: string
        query:
          description: The query field.
          readOnly: false
          type: string
        refs:
          description: The refs field.
          items:
            $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookRef'
          nullable: true
          readOnly: false
          type: array
      title: Webhooks Search Request
      type: object
      x-speakeasy-name-override: WebhooksSearchRequest
    c1.api.webhooks.v1.WebhookSource.WebhookSourcePolicyPostAction:
      description: The WebhookSourcePolicyPostAction message.
      nullable: true
      properties:
        ticketId:
          description: The ticketId field.
          readOnly: false
          type: string
      title: Webhook Source Policy Post Action
      type: object
      x-speakeasy-name-override: WebhookSourcePolicyPostAction
    c1.api.webhooks.v1.WebhookSource.WebhookSourceProvisionStep:
      description: The WebhookSourceProvisionStep message.
      nullable: true
      properties:
        ticketId:
          description: The ticketId field.
          readOnly: false
          type: string
      title: Webhook Source Provision Step
      type: object
      x-speakeasy-name-override: WebhookSourceProvisionStep
    c1.api.webhooks.v1.WebhooksServiceCreateResponse:
      description: The WebhooksServiceCreateResponse message.
      properties:
        webhook:
          $ref: '#/components/schemas/c1.api.webhooks.v1.Webhook'
      title: Webhooks Service Create Response
      type: object
      x-speakeasy-name-override: WebhooksServiceCreateResponse
    c1.api.webhooks.v1.Webhook:
      description: The Webhook message.
      properties:
        createdAt:
          format: date-time
          readOnly: true
          type: string
        deletedAt:
          format: date-time
          readOnly: true
          type: string
        description:
          description: The description field.
          readOnly: false
          type: string
        displayName:
          description: The displayName field.
          readOnly: false
          type: string
        id:
          description: The id field.
          readOnly: false
          type: string
        updatedAt:
          format: date-time
          readOnly: true
          type: string
        url:
          description: The url field.
          readOnly: false
          type: string
      title: Webhook
      type: object
      x-speakeasy-entity: Webhook
      x-speakeasy-name-override: Webhook
    c1.api.webhooks.v1.WebhookRef:
      description: The WebhookRef message.
      properties:
        id:
          description: The id field.
          readOnly: false
          type: string
      title: Webhook Ref
      type: object
      x-speakeasy-name-override: WebhookRef
    c1.api.webhooks.v1.WebhooksServiceCreateRequest:
      description: The WebhooksServiceCreateRequest message.
      properties:
        description:
          description: The description field.
          readOnly: false
          type: string
        displayName:
          description: The displayName field.
          readOnly: false
          type: string
        url:
          description: The url field.
          readOnly: false
          type: string
      required:
      - displayName
      - url
      title: Webhooks Service Create Request
      type: object
      x-speakeasy-name-override: WebhooksServiceCreateRequest
    c1.api.webhooks.v1.WebhooksSearchResponse:
      description: The WebhooksSearchResponse message.
      properties:
        list:
          description: The list field.
          items:
            $ref: '#/components/schemas/c1.api.webhooks.v1.Webhook'
          nullable: true
          readOnly: false
          type: array
        nextPageToken:
          description: The nextPageToken field.
          readOnly: false
          type: string
      title: Webhooks Search Response
      type: object
      x-speakeasy-name-override: WebhooksSearchResponse
    c1.api.webhooks.v1.WebhooksServiceTestRequestInput:
      description: The WebhooksServiceTestRequest message.
      title: Webhooks Service Test Request
      type: object
      x-speakeasy-name-override: WebhooksServiceTestRequest
    c1.api.webhooks.v1.WebhooksServiceListResponse:
      description: The WebhooksServiceListResponse message.
      properties:
        list:
          description: The list field.
          items:
            $ref: '#/components/schemas/c1.api.webhooks.v1.Webhook'
          nullable: true
          readOnly: false
          type: array
        nextPageToken:
          description: The nextPageToken field.
          readOnly: false
          type: string
      title: Webhooks Service List Response
      type: object
      x-speakeasy-name-override: WebhooksServiceListResponse
    c1.api.webhooks.v1.WebhookSource.WebhookSourceApprovalStep:
      description: The WebhookSourceApprovalStep message.
      nullable: true
      properties:
        ticketId:
          description: The ticketId field.
          readOnly: false
          type: string
      title: Webhook Source Approval Step
      type: object
      x-speakeasy-name-override: WebhookSourceApprovalStep
    c1.api.webhooks.v1.WebhookSource:
      description: "The WebhookSource message.\n\nThis message contains a oneof named source. Only a single field of the following list may be set at a time:\n  - test\n  - policyPostAction\n  - approvalStep\n  - provisionStep\n  - workflowStep\n"
      properties:
        approvalStep:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSource.WebhookSourceApprovalStep'
        policyPostAction:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSource.WebhookSourcePolicyPostAction'
        provisionStep:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSource.WebhookSourceProvisionStep'
        test:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSource.WebhookSourceTest'
        workflowStep:
          $ref: '#/components/schemas/c1.api.webhooks.v1.WebhookSource.WebhookSourceWorkflowStep'
      title: Webhook Source
      type: object
      x-speakeasy-name-override: WebhookSource
    c1.api.webhooks.v1.WebhooksServiceDeleteRequestInput:
      description: The WebhooksServiceDeleteRequest message.
      title: Webhooks Service Delete Request
      type: object
      x-speakeasy-name-override: WebhooksServiceDeleteRequest
    c1.api.webhooks.v1.WebhookSource.WebhookSourceWorkflowStep:
      description: The WebhookSourceWorkflowStep message.
      nullable: true
      properties:
        workflowExecutionId:
          description: The workflowExecutionId field.
          format: int64
          readOnly: false
          type: string
        workflowStepId:
          description: The workflowStepId field.
          readOnly: false
          type: string
      title: Webhook Source Workflow Step
      type: object
      x-speakeasy-name-override: WebhookSourceWorkflowStep
    c1.api.webhooks.v1.WebhooksServiceGetResponse:
      description: The WebhooksServiceGetResponse message.
      properties:
        webhook:
          $ref: '#/components/schemas/c1.api.webhooks.v1.Webhook'
      title: Webhooks Service Get Response
      type: object
      x-speakeasy-name-override: WebhooksServiceGetResponse
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
    oauth:
      description: 'This API uses OAuth2 with the Client Credential flow.

        Client Credentials must be sent in the BODY, not the headers.

        For an example of how to implement this, refer to the [c1TokenSource.Token()](https://github.com/ConductorOne/conductorone-sdk-go/blob/3375fe7c0126d17e7ec4e711693dee7b791023aa/token_source.go#L101-L187) function.'
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /auth/v1/token
      type: oauth2
